[package]
name = "mpsc_deadlock_reproducer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
core_affinity = "0.8.0"
thread-priority = "0.13.1"
